# Generated by Django 4.2.3 on 2023-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anekdot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя анекдота')),
                ('text', models.CharField(max_length=100, verbose_name='Содержание анекдота')),
            ],
            options={
                'verbose_name': 'Анекдот',
                'verbose_name_plural': 'Анекдоты',
            },
        ),
    ]
