# Generated by Django 4.2.3 on 2023-11-06 11:38

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рецепта')),
                ('text', models.TextField(verbose_name='Приготовление')),
                ('img', models.ImageField(help_text='Изоброжение блюда', upload_to=apps.common.models.common_img_name, verbose_name='Изоброжение блюда')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
