# Generated by Django 4.2.3 on 2023-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anekdot',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True, verbose_name='URL анектода'),
            preserve_default=False,
        ),
    ]
