# Generated by Django 4.2.3 on 2023-07-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_anekdot_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anekdot',
            name='slug',
        ),
        migrations.AlterField(
            model_name='anekdot',
            name='text',
            field=models.TextField(verbose_name='Содержание анекдота'),
        ),
    ]
