# Generated by Django 4.2.3 on 2023-08-06 13:59

import apps.slaider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мема')),
                ('img', models.ImageField(help_text='700x200px', upload_to=apps.slaider.models.poster_img_name, verbose_name='Изоброжение мема')),
            ],
            options={
                'verbose_name': 'Мем',
                'verbose_name_plural': 'Мемы',
            },
        ),
    ]
